---
- name: Check if Swarm is Already Initialized
  shell: docker node ls
  register: swarm_status
  ignore_errors: true

- name: Add Managers to the Swarm
  shell: "docker swarm join --token {{ hostvars['docker-swarm-1']['manager_token']['stdout'] }} {{ hostvars['docker-swarm-1']['ansible_eth0']['ipv4']['address'] }}:2377"
  when: swarm_status.rc != 0
  retries: 3
  delay: 20