# volumes
volumes:
  - device: /dev/vdb
    mountpoint: /data
  - device: /dev/vdc
    mountpoint: /var/lib/docker

# set docker proxy
proxy_env:
  HTTP_PROXY: http://wwwproxy.unimelb.edu.au:8000/
  HTTPS_PROXY: http://wwwproxy.unimelb.edu.au:8000/
  http_proxy: http://wwwproxy.unimelb.edu.au:8000/
  https_proxy: http://wwwproxy.unimelb.edu.au:8000/
  no_proxy: localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.u nimelb.edu.au,.cloud.unimelb.edu.au
    

# CouchDB configuration
user: user
pass: pass
VERSION: '3.2.1'
#cookie: ''
#uuid: ''