# Common vars
availability_zone: melbourne-qh2-uom
instance_image: 356ff1ed-5960-4ac2-96a1-0c0198e6a999
instance_key_name: test
instance_flavor: uom.mse.1c4g

# Volume
volumes:
  - vol_name: demo-vol-1-1
    vol_size: 10
  - vol_name: demo-vol-1-2
    vol_size: 10
  - vol_name: demo-vol-2-1
    vol_size: 10
  - vol_name: demo-vol-2-2
    vol_size: 10

# Security group
security_groups:
  - name: demo_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

# couchdb setup
- name: couchdb
    description: "Demo couchdb HTTP port"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0

# couchdb erlang-native clustered installation
- name: couchdb erlang
    description: "Demo couchdb erlang cluster HTTP port"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0
  
# couchdb cluster steup
- name: couchdb cluster
    description: "Demo couchdb cluster HTTP port"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_ip_prefix: 0.0.0.0/0


# Instance
instances:
  - name: demo-1
    volumes: ['demo-vol-1-1', 'demo-vol-1-2']
  - name: demo-2
    volumes: ['demo-vol-2-1', 'demo-vol-2-2']


